analytics: {}
color:
  brandColors:
    - '#D2D2D0'
    - '#DFE0E2'
    - '#171719'
    - '#B2B2AA'
    - '#252527'
  brandStrength: 0.731265
  lightness: 0.911318
  rhythmicContrast: 0.016046
  saturation: 0.716216
cta: {}
layout_spectrum: 0.822635
name: slowrivercoffee
opengraph: {}
purpose: []
typography_spectrum: 0.75
