name: slowrivercoffee
favicon: null
layout_spectrum: 0.49729
typography_spectrum: 0.75
title: Slow River Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7312659751623869
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
